services:
  db:
    image: postgres:16.2-alpine3.19
    container_name: mydb
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    ports:
      - "4444:5432"
  prometheus:
    image: prom/prometheus
    container_name: myprometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
  node-exporter:
    image: prom/node-exporter
    container_name: mynodeexporter
    ports:
      - "9100:9100"
  grafana:
    image: grafana/grafana-oss
    container_name: mygrafana
    ports:
      - "8080:3000"
    volumes:
      - grafana-data:/var/lib/grafana
volumes:
  grafana-data:
    driver: local